language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'

script: phpunit
before_install: wget http://getcomposer.org/composer.phar && php composer.phar install
env:
  global:
  - secure: "o6b1nDvq5u/CUB6v+koy3hGPA5HfmWNwraSXPOxp76F/jueme8bW9Cmdlq9Bsv80rPe6XDhT8UGrM37ZGmBPcxl5rDEYWk08utjAfdMfXFfIuanmOhtgC3C9uUM9CenYH0wI6seC6FFtetzxdJ6dUjVxHEq2KFoHO/1qSZ5Ub8LccARM8+sYkTFkQq2x9a3xsgUenG49hzN1al5sLVNA3N+nNT2sAn5xH7USwknuZR6yvyD5fdMiiaRjIXreTgDWgTaX9mO9V++eim8UFrv7pp4I3+lLhBUqRQGj+lRGRoCgA9WHCuMpaS/0jT19llORbMhSN71qFXzwRKKpBW1PPg8w+1/rQr2mOSfeMJQpsNaozbYOgrhosCg6SjFP48h43L9xMjztW5FSL+Z0LufgetPWJZMSTkXLNdH/SX4N2ewu2lZAeCmn1HDqQwfJek/NloUsRVKrcOhVLD41A+yHCxfwJaFvB5JBBc9FWsNGESJ3w4HUvixrQxc2EFy01KlZaApaKI8FBaT7lxuoXRfA/yl5YAR1QfWKXHVejk7wz83qHNfNczvsjuenHxfQQOpEVFiJY21/FbIrQBsM+Ar48IyS62mSbPD1GOgp7wf9Ll5dPnTQ3NP72FseTqL8idDIsXU8ZgIbnONc4rs0yQnWOEvWKo5Ojg8feWJ+z792o4Y="
  matrix:
  - MAILOSAUR_BASE_URL=https://mailosaur.com/api MAILOSAUR_SMTP_HOST=mailosaur.io
  - MAILOSAUR_BASE_URL=https://next.mailosaur.com/api MAILOSAUR_SMTP_HOST=ms-smtp.uk MAILOSAUR_USE_GENERATE=false
notifications:
  slack: mailosaur:CsJ9RruwjqHPKr1Iugk8GDtX
