language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'

script: phpunit
before_install: wget http://getcomposer.org/composer.phar && php composer.phar install
env:
  global:
  - secure: "SxzDD6lDvhCQ+edbmJhOPFLiK9VhiIyegu9ob27EF51cu8yE9gutR5zAyPPoPlamsJn7pzk2IJaJdt0c9gyEBZ3ZsmDgMGuWFlh6FALOQP4410teaD9u7BiNxRflVrayOZDJufCLoPkEAUzNCjUhTsHVEE6IolqhjRWpCamgjy30d0k09oJVPt2PIbqIOiw6l3ObvaLpWWo2PZ1YdlZAyL63yvqOYTvt2TU779QbLPkdNeWhfI7ZoxBmt+kz+cCxZ75Uxt0vo+q2buoTRa7ylPW2nFuhxUojraxdWxEprIApvspur4QAFU5/zS0/GqfaEwLlqaKbM5Br5ZzfH1VeFp/NYQtcQvDw7ZQ6uHc2Zze002uIvTFSyWdkUylpgl71aN887JdH4Tu1p7AH9R/LwFuQ9y9U+L+JZHnyhVVLM1Cqj+sI4tS0fYasEtfMn73J6uYCd0Kjl5ZGaUI2ri/uan+xn2ez8LHcE2EK1U0vd1EFfhPDupc7mu/eU1Zclt7fJwIygIMbo0pMbLzigNv4/mFaG+tV13m2GMmudHBD4BLdB3SScuZez2RVGHElmbEzSPutZ5DNtrHgtwoDtdvVOjcEyo0c1rJiICfaGpCeqnS1FRyN3BThJszRb2ULdcnOpJQT/twzmF53B09w21nKw0GwiCGDbleCxc4B9bnBznk="
  matrix:
  - MAILOSAUR_BASE_URL=https://mailosaur.com/ MAILOSAUR_SMTP_HOST=mailosaur.io
  - MAILOSAUR_BASE_URL=https://next.mailosaur.com/ MAILOSAUR_SMTP_HOST=ms-smtp.uk
notifications:
  slack: mailosaur:CsJ9RruwjqHPKr1Iugk8GDtX
