language: php
php:
- 5.3
script: phpunit
before_install: wget http://getcomposer.org/composer.phar && php composer.phar install
env:
  matrix:
    secure: pNsUIDBOn9Pq93Txf7DE1n19qMIh7A10YwiXu2o9x60M7u3wYTEotYApJodqmzkjjkUOyXdsM7W6+DmCNIpmuntV22e+Naw38zBvmXTgUxZBYi5vMDYRrWsPSTVArJ6Eb3gh0ytQ01TDPfQQmGCsKbOOdkwqA/Oj9KdjYbFI9Qegsk1cSQPBFXAuezhH6GaUbGC2VZuGyRjGjstJ8tVYWPz2oS1ej/vxCSdaIlL4q3O66raexbZychtIbg89hT6v6fkdQL2FPgQMocKEYOuWk/g7o1+oTtJ7pjtYjn5euxGal1CBV514ZI2z61rEfLhwBhQAno2yMWoIM1Zqd3Ifda0out2vff15tvPIPH9hYBRf+CCOj3N+z4nqyAz3YvTMptbwnHt85P3J0j6sLODUD8IE+YOBfkBm9HuF7dm5XYSERrn926RTVZSR4CMfznG3XQ6IjjOv4aHwv1CEIxqTfusGUqpT51nUjCU6EZHbC3FKEhU+cgYRno6FXhSp5MChoB6s/qmqjvaL/Rj/b4I5sGdvl4ctpoAxlA3cw4rGfnNeH3Htrm4GcVwYlvOW73N0uH30nFhOzJFJQadhOKZnHCx3EyOhtF0I3EXt3lN4IJsypMOR0wUa8JMg2xD4LWlO5Pi8CDJIneFJRRyAHKwmg6YX88WBsCw6gzxF8E3TsJE=
