language: php
php:
- 5.3
script: phpunit
before_install: wget http://getcomposer.org/composer.phar && php composer.phar install
env:
  global:
  - secure: OPz1WUzrehNv24oQYnDKsSr5Df0idgAZIRM4nodWUuzXsFrbTCV/CICHWkeXboZ9+9CnDEK/0eRJJL0fQ2Wl4W90c+z0yrUp91MqhPc4UMGS5WuGuCzE1iDwlbAI9aw/aR3l3Z7UaGvKr+tmLyxX2Q1LXaYi+RDwMzUXooRPz4zlcjXrzZSTy5khudHAfDTB8IshYd3jONx5eWfYsBWtJJQ3vAkju/bUI0wU2VFBfhqyTQ6Hw4f17GfeSNU2aE/YW7xDSu9RXqe13insRA0WMAd3Ro2qKCGPA6HjqW7KnvpNGciLtCKCBY+SW8Q0TpABK6l7N9MTCjLtqVUuWdXbOht8AZer1czKSR+RxiE37NjnIWbu6y3mdUarOGZYxhvj+pX8DvcWlZPWTJbRL6Hd+NKdckHcNweZfGDDlDDnats8rz/4nPwRP/hmqnTE/cWsM71rOSj5t6hGmEiWSftTk0bWM71w3N+5zLpSDu27nRAnLda6LhQEr8LDgVMQoIPL5fp+Y/6kgbaJCrMu55pgZwNqCOJLzWHs6dd93z7cR/uGFsbmI12HVsnqUPqn6HCbh99sKWSiaOLTtrb0heaEjYB0v8ZWsnCw029LIycAq7d7MySdL51JyYrLk9D4s5bB10sD8bfIX5pSD7QAACRlOClvxeD9gbXJ0GsxBGUAaiU=
  matrix:
  - MAILOSAUR_BASE_URL=https://mailosaur.com/api/ MAILOSAUR_SMTP_HOST=mailosaur.io
  - MAILOSAUR_BASE_URL=https://next.mailosaur.com/api/ MAILOSAUR_SMTP_HOST=ms-smtp.uk
notifications:
  slack:
    secure: dEufPHJxsXinke3pt8gMkCXe7h9kTe91YKLkoPk+LCbU7UzUd5mxK0uvOOkf2AhnGbxurPydfrTGbYNQzK5cKGKeB4B/bcDK2aSBdaUj3ApDNTEb7spTtmAClTZF5c+K29nx/k3yWi3BhuRXtCzN8nx35aC/hWMHYY4YsmRkWyCqZQEU2LdXew0RHaa96kkSobTu5eh8lcuC3WSnIMJZfKgDOta6zVl2HEuWLXN/HzgvvCXiA2KpH2mobeyHUkdpnKBkWWOgghPphZXF7dRAc+rkheIJHYHLtm5Crbg8+MIdvMM/u5ls9yLSNthXJlayJawUcB9xgnhEk+yTxaZKCkwS0LH1+vLw9gEr+kjhrcs9A91I9iwQcFT0g8L9JMg7MerEMb5ZpL42IuaBVCBe4L6KtkDzNIT2auYKyhrQdPsaGt4QUxT9UJ4HaknB7VqDLWSgHo8cI5uUrcR3vl8+gGvx3AMsaB2OXmvn1I6ZMbu7lxIhlP2gOVjFuJ9QpF4npc06tmxewUM66kS+vC7pUMK9riNL/6Jw8jHm0abUI4RC1Srtom/c35vEimgCoGuJrcPpU6FAYIt2fzB7tAgZyfNXfm9smhctsUyLzhqNM8HaPhya31PuXRejSvFIfl78O6mHgMmPrNqjgdEqqJuEt18SwWS38CrD8xHFy2UzEr4=
