language: php
php:
- 5.3
script: phpunit
before_install: wget http://getcomposer.org/composer.phar && php composer.phar install
env:
  matrix:
    secure: cQ3yleAYgGIs79ZgZYfbBC2downabQgeXIJwxKQ+a1AlE36tOHBnaM0s5o2G+HpGueZ6T7AGIdXsX2FH88RHLOXVzrVEZhyah9RTwFa7UmnAsdw6LG/8ud1ZVaWTPPmvsudscuLpo3SP2fTsrloIBC1XHKIcQpdwba3ritRbrmodclWngcBvNWF/3mUY3MFfe5Yoa2l21WApt9s/YENoDVAM4PPdSe81pReZijYyMBpjtIcVyNoEj0JtLY4MRcvDdtbS4TKU8stg2r8CzB0/t7INGxHDebOHLoGVCVX0MKIDyLj1XRY1XHc/WFMJ9D51FFHfRCMfZVfvMx8VPYudpHNV+/pUXFhGH3tD43cgpvH7Jh/H50+zE1x8INrtJQ8+qNCjidRyM+up83lTCEqShPWxYzmCqZW1rHL/bQfLX9ubMZqgrbY7xxACFet5vzczw2qnX6S1qyFZz4MTAAIa+cL3sCfRE0Gq/qqBfQsa5BY2YXmDWojUhmw5lKSsDndnOilUUGXC1nl3Laa8ZuQfJPKU6X6gbBeae1On2/JjxQF3ynhmvOBBcaTX7tdsve/cgE+9x3unE9ZvZ1NnX0mGEe8ToNXPi02QKhEI3AiRyUrivskgF7BX72IWx/ZDh6pbTtY8vJOobWbdAe9pxaJdM7TPyEkU0zNGQ9+dr6tYRxI=
