language: php
php:
- 5.3
script: phpunit
before_install: wget http://getcomposer.org/composer.phar && php composer.phar install
env:
  global:
  - secure: OPz1WUzrehNv24oQYnDKsSr5Df0idgAZIRM4nodWUuzXsFrbTCV/CICHWkeXboZ9+9CnDEK/0eRJJL0fQ2Wl4W90c+z0yrUp91MqhPc4UMGS5WuGuCzE1iDwlbAI9aw/aR3l3Z7UaGvKr+tmLyxX2Q1LXaYi+RDwMzUXooRPz4zlcjXrzZSTy5khudHAfDTB8IshYd3jONx5eWfYsBWtJJQ3vAkju/bUI0wU2VFBfhqyTQ6Hw4f17GfeSNU2aE/YW7xDSu9RXqe13insRA0WMAd3Ro2qKCGPA6HjqW7KnvpNGciLtCKCBY+SW8Q0TpABK6l7N9MTCjLtqVUuWdXbOht8AZer1czKSR+RxiE37NjnIWbu6y3mdUarOGZYxhvj+pX8DvcWlZPWTJbRL6Hd+NKdckHcNweZfGDDlDDnats8rz/4nPwRP/hmqnTE/cWsM71rOSj5t6hGmEiWSftTk0bWM71w3N+5zLpSDu27nRAnLda6LhQEr8LDgVMQoIPL5fp+Y/6kgbaJCrMu55pgZwNqCOJLzWHs6dd93z7cR/uGFsbmI12HVsnqUPqn6HCbh99sKWSiaOLTtrb0heaEjYB0v8ZWsnCw029LIycAq7d7MySdL51JyYrLk9D4s5bB10sD8bfIX5pSD7QAACRlOClvxeD9gbXJ0GsxBGUAaiU=
  matrix:
  - MAILOSAUR_BASE_URL=https://mailosaur.com/api/ MAILOSAUR_SMTP_HOST=mailosaur.io
  - MAILOSAUR_BASE_URL=https://next.mailosaur.com/api/ MAILOSAUR_SMTP_HOST=ms-smtp.uk MAILOSAUR_USE_GENERATE=false
notifications:
  slack: mailosaur:CsJ9RruwjqHPKr1Iugk8GDtX
